Feature/itl 9 implement multiple page todo app
aronnorbert24/ToDoApp pull request #12
Opened 2023-09-07 07:51 UTC by aronnorbert24

2023-09-07 08:39 UTC, tamasm-wg requested changes
My concern right now is how you save the password , once you fix that I will review the other parts also

2023-09-07 08:39 UTC, tamasm-wg commented on server/src/services/userService.ts
> +
You can't just store the users password as it is in the database. Please lookup password hashing and salting.

2023-09-07 08:39 UTC, tamasm-wg commented on server/src/services/userService.ts
> +    console.log(savedUser)
remove console.log

2023-09-07 08:39 UTC, tamasm-wg commented on client/src/views/RegisterPage.vue
> +      <UserInput :label="'First Name:'" :property="'firstName'" v-model="user.firstName" />
if you just want to pass a string as prop you don't need to use bind ( : ) so instead of :label="'First Name'" you can do label="First Name"

2023-09-07 08:39 UTC, tamasm-wg commented on client/src/services/authentication.ts
> +    const response = await axios.post(`${import.meta.env.VITE_BASE_URL}/register-user`, {
please lookup password hashing and salting

2023-09-07 08:41 UTC, gerebdavid commented on client/src/components/baseComponents/UserInput.vue
> +  set: (newValue) => emit('update:modelValue', newValue, props.label),
Why you need to send the label?

2023-09-07 09:04 UTC, gerebdavid commented on client/src/views/HomeDashboard.vue
> +  id: -1,
Why do you need two ids?

2023-09-07 09:05 UTC, gerebdavid commented on client/src/views/HomeDashboard.vue
> +    id: todo.id,
Double ids

2023-09-07 09:07 UTC, gerebdavid commented on client/src/views/LoginPage.vue
> +    errorMessage.value = 'Registration failed. Please check your input and try again.'
The error message should come from the BE

2023-09-07 09:08 UTC, gerebdavid commented on client/src/views/LoginPage.vue
> +      <UserInput :label="'Email:'" :property="'email'" v-model="email" />
You finished the whole front end part of the Todo project, now you have to create a Login page and we still see stuff like this... Please pay more attention.

2023-09-07 09:10 UTC, gerebdavid commented on client/src/views/RegisterPage.vue
> +    errorMessage.value = 'Registration failed. Please check your input and try again.'
Again, error message should come from the BE

2023-09-07 09:11 UTC, gerebdavid commented on client/src/views/RegisterPage.vue
> +    console.log(user.value)
delete console log if not needed

2023-09-07 09:13 UTC, gerebdavid commented on server/src/controllers/userController.ts
> +      return res.sendStatus(400)
Why you sending 400 error code from here but 500 from register?

2023-09-07 14:31 UTC, tamasm-wg requested changes

2023-09-07 14:31 UTC, tamasm-wg commented on server/src/controllers/userController.ts
> +      if (duplicateUser) {
if you use an early return you don't need the else condition

2023-09-07 14:31 UTC, tamasm-wg commented on server/src/middleware/ValidateSchema.ts
> +
if you added Joi , please validate the Todo schema as well

2023-09-07 14:31 UTC, tamasm-wg commented on client/src/views/LoginPage.vue
> +/* eslint-disable @typescript-eslint/no-explicit-any */
please modify your tsconfig instead of writing this at the beginning of multiple components

2023-09-07 14:31 UTC, tamasm-wg commented on client/src/views/RegisterPage.vue
> +    await registerUser(user.value)
use one request for this please

2023-09-07 14:31 UTC, tamasm-wg commented on server/src/controllers/userController.ts
> +
where is the return ?

2023-09-07 14:31 UTC, tamasm-wg commented on server/src/controllers/userController.ts
> +
return ?

2023-09-08 10:51 UTC, gerebdavid commented on client/src/components/baseComponents/UserInput.vue
> +      :type="property"
I dont think firstName, lastName is a valid input type...

2023-09-08 13:21 UTC, tamasm-wg requested changes

2023-09-08 13:21 UTC, tamasm-wg commented on server/src/routes/router.ts
> +router.post('/register-user', ValidateSchema(Schemas.user.register), userController.register)
i suggest naming the route just register, what else are you going to register besides users ?

2023-09-08 13:21 UTC, tamasm-wg commented on server/src/middleware/ValidateSchema.ts
> +  post: {
you have posts or todos ?

2023-09-08 14:14 UTC, gerebdavid approved these changes

2023-09-10 07:58 UTC, merged