Feature/itl 6 add sorting functionality
aronnorbert24/ToDoApp pull request #8
Opened 2023-08-29 08:00 UTC by aronnorbert24

2023-08-29 09:13 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +        :class="[
computed

2023-08-29 09:14 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +const buttons: string[] = ['Title', 'Description', 'Priority', 'Date']
Add more descriptive name

2023-08-29 09:22 UTC, gerebdavid commented on src/components/TodoApp.vue
> +const isShowingEmptyImage = computed(() => !isShowingForm.value && !todos.value.length)
Rename this to isEmptyImageVisible

2023-08-29 09:23 UTC, gerebdavid commented on src/components/TodoApp.vue
> +  const allTodos = [...todos.value]
This variable not needed, you can filter todos.value right away

2023-08-29 09:29 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +  if (activeSort.value !== priority && !isSortActive.value) {
Please explain the logic of this function

2023-08-29 09:30 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +    return isAscendingActive.value ? ['border-green-400', 'bg-green-400'] : ['border-black', 'bg-black']
Why you pass classes as array if on other cases you used strings?

2023-08-29 09:33 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +    return isAscendingActive.value ? ['border-green-400', 'bg-green-400'] : ['border-black', 'bg-black']
Why you pass classes as array if on other cases you used strings?

2023-08-29 09:33 UTC, gerebdavid commented on src/components/ToDoSort.vue
> +  order !== sortOrder.value ? (isAscendingActive.value = !isAscendingActive.value) : ''
Dont use ternary if you dont return anything in the "else". Use if instead

2023-08-29 09:34 UTC, gerebdavid commented on src/components/TodoApp.vue
> +  let fa = a.title.trim().toLowerCase(),
Add more descriptive variable name, also dont forget what we talked about declaring multiple variables

2023-08-29 10:29 UTC, kincsokiss requested changes

2023-08-29 10:29 UTC, kincsokiss commented on src/components/ToDoSort.vue
> +  isSortActive.value && activeSort.value.length
Please see David's comment above: use if statement instead of the ternary if you don't return anything in the else part.

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
>  const isShowingForm: Ref<boolean> = ref(false)
Please rename this to `isFormShown`

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
>  function toggleCheck(checked: boolean, id: number) {
Please rename the `checked` to `isChecked`

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +function animate(id: number, checked: boolean) {
Same here, `isChecked`

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +  isSortActive.value ? sortTodos(activeProperty.value, activeOrder.value, isSortActive.value) : ''
Change the ternary to if.

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +  isSortActive.value ? sortTodos(activeProperty.value, activeOrder.value, isSortActive.value) : ''
Same here, if instead of ternary.

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +  let fa = new Date(a.dueDate)
If the value of the variable is not changed please use `const` instead of `let`.

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +  if (activeOrder.value === 'ascending') {
You can use ternary in this case: 
`return activeOrder.value === 'ascending' ? fa - fb : fb - fa`

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +  if (activeOrder.value === 'ascending') {
Please use ternary.

2023-08-29 10:29 UTC, kincsokiss commented on src/components/TodoApp.vue
> +    fb = priorityOrder.indexOf(b.priority)
Is `fb` declared somewhere?

2023-08-29 11:45 UTC, kincsokiss approved these changes

2023-08-30 06:51 UTC, gerebdavid approved these changes

2023-08-30 06:54 UTC, merged